### ISSUE TITLE
7zip error

### ISSUE THREAD

**Issue by fnbgy** [VRPirates/rookie#143]
When I try to sideload a game it just says 
7zip error: Extracting failed: The system cannot find the path specified. and 
![Screenshot (6)](https://github.com/user-attachments/assets/1d113708-e144-4ba9-8b28-d441b8567048)
![Screenshot (7)](https://github.com/user-attachments/assets/9a672b9b-8e4e-4da6-9877-01614026e7df)

Output: 
Error: Extract Failed

**Comment by frxctura** [comment]
Please refer to the readme.
https://github.com/VRPirates/rookie#disclaimer
https://github.com/VRPirates/rookie#support

**Comment by fnbgy** [comment]
I did

**Comment by Akhil16** [comment]
I updated to version 1.30.* and facing the same issue, was able to use earlier smoothly

**Comment by Fenopy** [comment]
From our support FAQs

**7zip error**
7-Zip errors are usually caused by your Anti-Virus blocking rclone from downloading files. Add an Exception to your Rookie folder to prevent this problem.
You may also need to add Rookie/rclone/rclone.exe as an Exception.

[VRP Wiki](https://vrpirates.wiki/)
[Is Rookie a Virus?](https://vrpirates.wiki/en/general_information/Sideloading-FAQ#is-rookie-a-virus:same)

[Rookie Git](https://github.com/VRPirates/rookie)

[Add an Exclusion to Windows Defender](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26)
