### ISSUE TITLE
Direct download vs. 'Copy OBB' button issue

### ISSUE THREAD

**Issue by Sombody101** [VRPirates/rookie#151]
Hi, I'm the developer of APKonito and I've had some users say that there are issues with select games not loading after running them through APKognito. I've narrowed it down to the difference between sideloading the game manually and automatically after downloading.

To get to the point, it's the [ADB.CopyOBB()](https://github.com/VRPirates/rookie/blob/58aa1be7c51dd128fc0800ac1ba6eb1e6af4e465/MainForm.cs#L842) method vs. [ADB.RunAdbCommandToString()](https://github.com/VRPirates/rookie/blob/58aa1be7c51dd128fc0800ac1ba6eb1e6af4e465/MainForm.cs#L3052) (using ADB 'push'). The reason this is causing problems for some users is that games like Walkabout Mini Golf have bundle files in the same directory as the OBB that need to be pushed to the device along with the OBB file which aren't being sideloaded with the OBB.

I'm not making a PR with a fix for this because I'm not sure how you guys would prefer to solve this in comparison to my solution.
If you'd like a little more information on what's happening feel free to ask. Thanks!

**Comment by frxctura** [comment]
Hi there,

Thanks for bringing this to our attention. Just to clarify, the CopyOBB method isn't designed to selectively push .obb files. It pushes everything in the provided folder, as the method is intended to handle any contents of the OBB directory, not just individual files. If bundle files are being missed, it might be due to how the folder is being structured before using your tool. However, this hasn't been an issue with Rookie, which has been performing the same operations for quite a while without causing any problems.

Regarding your decision not to submit a PR — there's really no need to hold back. We encourage contributions, and we can always review and accept or reject them as appropriate. That's the whole point of code reviews, after all.

As for your reluctance to provide more details, it’s a bit puzzling. If users are encountering issues, we’d appreciate more context (error logs, specific steps, etc.) so we can understand the problem. It's generally more effective if you share these details up front rather than leaving us to wonder. After all, the more information we have, the quicker we can help, rather than playing a guessing game.

**Comment by frxctura** [comment]
For more context, here’s the method in question: [CopyOBB Method](https://github.com/VRPirates/rookie/blob/master/ADB.cs#L30). 

You can also see where it's used in the MainForm.cs here:

- [MainForm.cs - Line 842](https://github.com/VRPirates/rookie/blob/master/MainForm.cs#L842C21-L842C59)
- [MainForm.cs - Line 1458](https://github.com/VRPirates/rookie/blob/master/MainForm.cs#L1458C29-L1458C57)
- [MainForm.cs - Line 1574](https://github.com/VRPirates/rookie/blob/master/MainForm.cs#L1574C28-L1574C59)
- [MainForm.cs - Line 1701](https://github.com/VRPirates/rookie/blob/master/MainForm.cs#L1701C29-L1701C57)

You’ll notice in the last example, we even have a comment explaining how Rookie will automatically recreate the OBB folder if an OBB file is dragged and dropped.

If you have a fix in mind, there's no reason to hesitate in submitting a PR. We're more than happy to review it and make any necessary adjustments.

**Comment by Sombody101** [comment]
Apologies on my part- I did not see that there was a concatenation off-screen in the `CopyOBB` method which performed the ADB push. My initial glance at the method only showed that a deletion was performed. That's my fault for not looking further and rushing to conclusions.

The reason I assumed it was due to the way Rookie was uploading files was because when I tested it, all files did not show up in their respective OBB folder with only the OBB file itself present. Knowing what I know now, there was obviously something wrong with the way I tested the feature. I'll look into my codebase to see if the error for this was in fact on my end and not yours or Rookie's.

I'll close this ticket as clearly, there's nothing wrong. If I do find an issue, I'll be sure to make a PR with possible fixes.
Thanks!
