### ISSUE TITLE
7zip error

### ISSUE THREAD

**Issue by xDerApfelx** [VRPirates/rookie#168]
After downloading a game i get this error code. I looked at the other issues posted here. I completely deactivated windows defender and changed the download folder to somewhere else it didn't work at all. nothing helped. Yesterday everything worked fine. I didnt change anything.

![image](https://github.com/user-attachments/assets/0cc53538-2046-414a-aec6-f825749e3d77)
![image](https://github.com/user-attachments/assets/81e575fa-da68-480a-b513-9283368df760)

**Comment by SoufianeMaski** [comment]
Hey it's the same for me also. I get the same error when I finish a downloaded game 

But for some some games I faced also this issue, where the game wouldn't even start downloading : 
![image](https://github.com/user-attachments/assets/eb8bca5b-496c-48dc-a917-05ea1429875f)

**Comment by KnuXles** [comment]
Successfully recreated both errors above. I am also getting similar issues with various other games. I have the antivirus exception set up correctly, am using a simple directory path which has worked every time up until this weekend and I have tried the "delete game after install" option both on and off.

Example 1: downloads, but once it reaches the extracting stage it give this error
![image](https://github.com/user-attachments/assets/a6fbf4f5-892a-4eac-9d47-fc877fffcbcf)
Example 2: downloads again, but once it finishes file 1 of 2 it throws this error. And I know this one worked recently because I was trying to re-install it after a game-breaking glitch (cat disappeared lol)
![image](https://github.com/user-attachments/assets/c6a31d07-ad2b-48da-a1cf-1cc84706a48e)

**Comment by frxctura** [comment]
This is not an application issue.
