### ISSUE TITLE
Unable to connect to Remote Server

### ISSUE THREAD

**Issue by georgewoodall82** [VRPirates/rookie#93]
this is a duplicate of #86 because its not fixed.

But there is a solution, I created a blank file called "vrp-public.json" in the rookie folder and it worked fine.

**Comment by Chax1** [comment]
So, expected behaviour, so the need to make this issue post was pretty much 0.
Do not make issue posts for things that are expected behaviour/not an application issue, such as, not connecting when you don't have the file the program needs to connect.

**Comment by georgewoodall82** [comment]
the file doesn't come with the program by default so yes this is an issue.

**Comment by Chax1** [comment]
No, it is not an issue, just because you think it is doesn't make it one.

You're not supposed to download just the binary from this GitHub, and if you do, you're expected to know how to deal with it, we package all our releases on our wiki with the file needed and Rookie CAN work without depending what you want to connect to.

Stop telling me what is or isn't an issue, I've been maintaining this program for 2 years, I am more than very well aware as to what IS expected behaviour and what isn't.

**Comment by Fenopy** [comment]
Rookie is open source and can be used to download from a multitude of mirrors. The json file is specifically for the current VRP Public Mirror.
I realize this seems like an issue, but the application itself is built for functioning with many types of mirrors and is not specific to the VRP Public Mirror.
